<?php

namespace Cougar\UnitTests\Autoload;

use Cougar\Autoload\Autoload;
use Cougar\Autoload\FlexAutoload;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-06 at 16:26:53.
 */
class FlexAutoloadTest extends \PHPUnit_Framework_TestCase {

    public static function setUpBeforeClass()
    {
        require_once(__DIR__ . "/../../Cougar/Autoload/FlexAutoload.php");
        require_once(__DIR__ . "/../../Cougar/Cache/CacheFactory.php");
        require_once(__DIR__ . "/../../Cougar/Cache/iCache.php");
        require_once(__DIR__ . "/../../Cougar/Cache/Cache.php");
    }

    /**
     * @covers Cougar\Autoload\FlexAutoload::addPath
     */
    public function testAddPath()
    {
        # Get the original include path
        $orig_include_path = get_include_path();

        # Set the path to something we know
        set_include_path("/usr/share/pear");

        # Add the the TestClass path
        $new_path = __DIR__ . DIRECTORY_SEPARATOR . "TestClass";
        FlexAutoload::addPath($new_path);

        # Make sure our splAutoload method is there
        $spl_autoload_functions = spl_autoload_functions();
        $this->assertEquals(
            array("Cougar\\Autoload\\FlexAutoload", "splAutoload"),
            end($spl_autoload_functions));

        # Compare the value of the path to what it should be
        $this->assertEquals($new_path . PATH_SEPARATOR . "/usr/share/pear",
            get_include_path());

        # Restore the original include path
        set_include_path($orig_include_path);
    }

    /**
     * @covers Cougar\Autoload\FlexAutoload::addPath
     */
    public function testAddPathWithDot()
    {
        # Get the original include path
        $orig_include_path = get_include_path();

        # Set the path to something we know
        set_include_path("." . PATH_SEPARATOR . "/usr/share/pear");

        # Add the the TestClass path
        $new_path = __DIR__;
        FlexAutoload::addPath($new_path);

        # Make sure our splAutoload method is there
        $spl_autoload_functions = spl_autoload_functions();
        $this->assertEquals(
            array("Cougar\\Autoload\\FlexAutoload", "splAutoload"),
            end($spl_autoload_functions));

        # Compare the value of the path to what it should be
        $this->assertEquals("." . PATH_SEPARATOR . $new_path . PATH_SEPARATOR .
            "/usr/share/pear", get_include_path());

        # Restore the original include path
        set_include_path($orig_include_path);
    }

    /**
     * @covers Cougar\Autoload\FlexAutoload:;splAutoload
     * @depends testAddPath
     */
    public function testAutoloadClassImplementingInterface()
    {
        # Create a new AutoloadTestClass object
        $object = new TestClass\AutoloadTestClass();
        $this->assertInstanceOf(
            "Cougar\UnitTests\Autoload\TestClass\AutoloadTestClass", $object);
    }
}
