<?php

namespace Cougar\UnitTests\Autoload;

use Cougar\Autoload\Autoload;
use Cougar\Autoload\FlexAutoload;

require_once(__DIR__ . "/../../Cougar/Autoload/Autoload.php");

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-06 at 16:26:53.
 */
class FlexAutoloadTest extends \PHPUnit_Framework_TestCase {

    /**
     * @covers Cougar\Autoload\FlexAutoload:;addpath
     */
    public function testAddPath()
    {
        # Ensure we can autoload
        Autoload::register(dirname(dirname(__DIR__)));

        # Get the number of autoload functions and the include path
        $function_count = count(spl_autoload_functions());
        $orig_include_path = get_include_path();

        # Add the the TestClass path
        FlexAutoload::addPath(__DIR__ . DIRECTORY_SEPARATOR . "TestClass");

        # Count should now be pervious count + 1
        $this->assertEquals($function_count + 1,
            count(spl_autoload_functions()));

        # Include path should not be the same
        $this->assertNotEquals($orig_include_path, get_include_path());
    }
    
    /**
     * @covers Cougar\Autoload\FlexAutoload:;splAutoload
     * @depends testAddPath
     */
    public function testAutoloadClassImplementingInterface()
    {
        # Create a new AutoloadTestClass object
        $object = new TestClass\AutoloadTestClass();
        $this->assertInstanceOf(
            "Cougar\UnitTests\Autoload\TestClass\AutoloadTestClass", $object);
    }
}
