<?php

namespace Cougar\UnitTests\RestService;

use Cougar\Security\Security;
use Cougar\RestService\AnnotatedRestService;
use Cougar\Util\Xml;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-18 at 12:50:03.
 */
class AnnotatedRestServiceTestGet extends \PHPUnit_Framework_TestCase {

    /**
     * @var AnnotatedRestService
     */
    protected $object;

    public static function setUpBeforeClass()
    {
        require_once(__DIR__ . "/../../cougar.php");
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testSimpleCase() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/SimpleCase";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize($object->simpleCase()));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testSingleUriArgument() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/SingleUriArgument/uri1";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->singleUriArgument("uri1")));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testMultiUriArgument() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/MultiUriArgument/uri1/uri2/uri3";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->multiUriArgument("uri1", "uri2", "uri3")));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testMultiUriArgumentPlus() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/MultiUriArgument/plus/uri1/uri2/uri3";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->multiUriArgumentPlus(array("uri1", "uri2", "uri3"))));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testMultiUriArgumentWithLiteral() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/MultiUriArgument/uri1/literal/uri2";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->multiUriArgumentWithLiteral("uri1", "uri2")));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testEmptyResponse() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/EmptyResponse";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString("");
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testGetValueOneArgumentSpaceAtEnd()
    {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/GetValue/OneArg/Space/At/End";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        $_GET["something"] = "foo";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->getValueOneArgumentSpaceAtEnd("foo")));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testSingleGetArgumentFloat() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/GetValue/OneArg/float";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        $_GET["float"] = "3.5";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->getValueOneArgumentFloat(3.5)));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testSingleGetArgumentString() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/GetValue/OneArg/string";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        $_GET["string"] = "three";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->getValueOneArgumentString('three')));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testSingleGetArgumentInt() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/GetValue/OneArg/int";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        $_GET["int"] = "3";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->getValueOneArgumentInt(3)));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testSingleGetArgumentBool() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/GetValue/OneArg/bool";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        $_GET["bool"] = "true";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->getValueOneArgumentBool(true)));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testGetValueOneGetArgumentOnePostArgument()
    {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/GetValue/OneArg/Space/At/End";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        $_GET["something"] = "foo";
        $_POST["somethingelse"] = "bar";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->getValueOneArgumentSpaceAtEnd("foo")));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     * @expectedException \Cougar\Exceptions\MethodNotAllowedException
     */
    public function testGetWithPost() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_SERVER["REQUEST_URI"] = "/get/SimpleCase";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
        $this->fail("Expected exception was not thrown");
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     * @expectedException \Cougar\Exceptions\BadRequestException
     */
    public function testNonExistantEndPoint() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/whatever";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
        $this->fail("Expected exception was not thrown");
    }
            
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testGetBody() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/with/body";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        global $_BODY;
        $_BODY = "Sample Body";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize($object->GetBody($_BODY)));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     * @expectedException \Cougar\Exceptions\BadRequestException
     */
    public function testOptionsWithGet() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "OPTIONS";
        $_SERVER["REQUEST_URI"] = "/get/SimpleCase";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
        $this->fail("Expected exception was not thrown");
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testJson() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/SimpleCase";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/json";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(json_encode($object->simpleCase()));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testXML() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/SimpleCase";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/xml";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(Xml::toXml($object->simpleCase()));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
        
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testHTML() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/SimpleCase";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "text/html";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(Xml::toXml($object->simpleCase()));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testJsonContentType() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/ContentType";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/json";
        $_SERVER["HTTP_CONTENT_TYPE"] = "application/json";
        
        $object = new \stdClass();
        $object->foo = "bar";
        $json_object = json_encode($object);
        
        global $_BODY;
        $_BODY = $json_object;
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(json_encode(
                $object->PostBodyJson($json_object)));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testXmlContentType() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/ContentType";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/xml";
        $_SERVER["HTTP_CONTENT_TYPE"] = "application/xml";
        
        $xml = new \SimpleXMLElement("<foo><bar id=\"1\"/></foo>");
        $xml_text = $xml->asXML();
        
        global $_BODY;
        $_BODY = $xml_text;
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString($object->PostBodyXml($xml_text));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testDefaultValueNoValue()
    {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/with/default/value";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize($object->getDefaultValue()));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testDefaultValueWithValue()
    {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/with/default/value";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        $_GET["default"] = "other value";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->getDefaultValue("other value")));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testMultiplePaths1() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/with/multiple/paths/constant/MyVar";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->getMultiplePaths("MyVar")));

        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
    
    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testMultiplePaths2() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/with/multiple/paths/MyVar/constant";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";
        
        $object = new AnnotatedRestServiceGetTests();
        $this->expectOutputString(serialize(
            $object->getMultiplePaths("MyVar")));
        
        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testMultipleBindings() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/SimpleCase";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";

        $object = new AnnotatedRestServiceGetTests();
        $object2 = new AnnotatedRestServiceGetAdditionalBindingTests();

        $this->expectOutputString(serialize($object->simpleCase()));

        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->bindFromObject($object2);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testMultipleBindingsSecondBinding() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/additional/binding/simpleCase";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";

        $object = new AnnotatedRestServiceGetTests();
        $object2 = new AnnotatedRestServiceGetAdditionalBindingTests();

        $this->expectOutputString(serialize($object2->additionalSimpleCase()));

        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->bindFromObject($object2);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testMultipleBindingsReverse() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/SimpleCase";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";

        $object = new AnnotatedRestServiceGetTests();
        $object2 = new AnnotatedRestServiceGetAdditionalBindingTests();

        $this->expectOutputString(serialize($object->simpleCase()));

        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object2);
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testMultipleBindingsReverseSecondBinding() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/additional/binding/simpleCase";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/vnd.php.serialized";

        $object = new AnnotatedRestServiceGetTests();
        $object2 = new AnnotatedRestServiceGetAdditionalBindingTests();

        $this->expectOutputString(serialize($object2->additionalSimpleCase()));

        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object2);
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testObjectMagicMethodResponseJson() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/return/magic/method";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/json";

        $object = new AnnotatedRestServiceGetTests();

        $this->expectOutputString(json_encode($object->getReturnMagicMethod()));

        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testObjectMagicMethodResponseXml() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/return/magic/method";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "application/xml";

        $object = new AnnotatedRestServiceGetTests();

        $this->expectOutputString($object->getReturnMagicMethod()->__toXml());

        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }

    /**
     * @covers \Cougar\RestService\RestService::bindFromObject
     * @covers \Cougar\RestService\RestService::handleRequest
     */
    public function testObjectMagicMethodResponseHtml() {
        $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1";
        $_SERVER["REQUEST_METHOD"] = "GET";
        $_SERVER["REQUEST_URI"] = "/get/return/magic/method";
        $_SERVER["PHP_SELF"] = "/request_handler";
        $_SERVER["HTTP_HOST"] = "localhost";
        $_SERVER["HTTP_ACCEPT"] = "text/html";

        $object = new AnnotatedRestServiceGetTests();

        $this->expectOutputString($object->getReturnMagicMethod()->__toHtml());

        $service = new AnnotatedRestService(new Security());
        $service->bindFromObject($object);
        $service->handleRequest();
    }
}

class AnnotatedRestServiceGetTests
{
    /**
     * @Path /get/SimpleCase
     * @Methods GET
     */
    public function simpleCase()
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/SingleUriArgument/:argument
     */
    public function singleUriArgument($argument)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/MultiUriArgument/:argument1/:argument2:/:argument3
     */
    public function multiUriArgument($argument1, $argument2, $argument3)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/MultiUriArgument/plus/:arguments+
     */
    public function multiUriArgumentPlus(array $arguments)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/MultiUriArgument/:argument1/literal/:argument2
     */
    public function multiUriArgumentWithLiteral($argument1, $argument2)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }

    /**
     * @Path /get/EmptyResponse
     */
    public function emptyResponse()
    {
        # Don't return anything; response should be blank
    }
    
    /**
     * @Path /get/GetValue/OneArg/Space/At/End
     * @GetValue something  
     */
    public function getValueOneArgumentSpaceAtEnd($something)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/GetValue/OneArg/float
     * @GetValue float float  
     */
    public function getValueOneArgumentFloat($float)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/GetValue/OneArg/string
     * @GetValue string string  
     */
    public function getValueOneArgumentString($string)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/GetValue/OneArg/int
     * @GetValue int int  
     */
    public function getValueOneArgumentInt($int)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/GetValue/OneArg/bool
     * @GetValue bool bool  
     */
    public function getValueOneArgumentBool($bool)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/GetValue/OneArg/Space/At/End
     * @GetValue something  
     * @PostValue somethingelse
     */
    public function getValueOneGetArgumentOnePostArgument($something, $somethingelse)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }    
        
    /**
     * @Path /get/with/body
     * @Methods GET
     * @Body body
     */
    public function getBody($body)
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/ContentType
     * @Methods GET
     * @Body body
     * @Accepts JSON
     */
    public function postBodyJson($body)
    {
        $json = json_decode($body);
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/ContentType
     * @Methods GET
     * @Body body
     * @Accepts XML
     */
    public function postBodyXml($body)
    {
        $xml = new \SimpleXMLElement($body);
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
    
    /**
     * @Path /get/with/default/value
     * @Methods GET
     * @GetValue default
     */
    public function getDefaultValue($default = "default value")
    {
        return array("method" => __FUNCTION__,
            "argument" => $default);
    }
    
    /**
     * @Path /get/with/multiple/paths/constant/:variable
     * @Path /get/with/multiple/paths/:variable/constant
     * @Methods GET
     */
    public function getMultiplePaths($variable)
    {
        return array("method" => __FUNCTION__,
            "argument" => $variable);
    }

    /**
     * @Path /get/return/magic/method
     * @Methods GET
     */
    public function getReturnMagicMethod()
    {
        return new SampleObjectWithXmlAndHtmlExport();
    }
}

class AnnotatedRestServiceGetAdditionalBindingTests
{
    /**
     * @Path /get/additional/binding/simpleCase
     * @Methods GET
     */
    public function additionalSimpleCase()
    {
        return array("method" => __FUNCTION__,
            "arguments" => func_get_args());
    }
}

class SampleObjectWithXmlAndHtmlExport
{
    public $foo = "bar";
    public $bar = "foo";

    public function __toHtml()
    {
        return "<div>Foo/Bar</div>";
    }

    public function __toXml()
    {
        return "<foo>bar</foo>";
    }
}
